name: Opencore Secure Boot Generator
on:
  workflow_dispatch:
    inputs:
      version: 
        description: 'Version to create'
        default: '0.9.3'
        required: true
        type: string
env:
  LEVEL: ${{ inputs.version }}
jobs:
  Get-Opencore:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Run sbsigntool
      run: |
            wget -q "https://github.com/acidanthera/OpenCorePkg/releases/download/${{ inputs.version }}/OpenCore-${{ inputs.version }}-RELEASE.zip"
            unzip -o "OpenCore-${{ inputs.version }}-RELEASE.zip" "X64/*" -d "./Downloaded"
            wget -q https://github.com/acidanthera/OcBinaryData/raw/master/Drivers/HfsPlus.efi -O ./Downloaded/X64/EFI/OC/Drivers/HfsPlus.efi
            rm -rf "OpenCore-${{ inputs.version }}-RELEASE.zip"
            find ./Downloaded/X64/EFI/**/* -type f -name "*.efi" ! -name '.*' | cut -c 3- | xargs -I{} bash -c 'sbsign --key ISK.key --cert ISK.pem --output $(mkdir -p $(dirname "./Signed/{}") | echo "./Signed/{}") ./{}'
            rm -rf Downloaded
    - uses: actions/upload-artifact@v2
  
      with:
        name: ${{ inputs.version }}
        path: "/home/runner/work/opencore-secure-boot/opencore-secure-boot/Signed/Downloaded/X64/"
