name: Opencore Secure Boot Generator
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version: 
      # Friendly description to be shown in the UI instead of 'name'
        description: 'Version to create'
        # Default value if no value is explicitly provided
        default: '0.9.3'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "$version"
        env:
          LEVEL: ${{ inputs.version }}
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Run sbsigntool
      run: wget -q "https://github.com/acidanthera/OpenCorePkg/releases/download/${{ inputs.version }}/OpenCore-${{ inputs.version }}-RELEASE.zip";unzip "OpenCore-${{ inputs.version }}-RELEASE.zip" "X64/*" -d "./Downloaded"
    - uses: stefanzweifel/git-auto-commit-action@v4
